apiVersion: management.loft.sh/v1
kind: VirtualClusterInstance
metadata:
  name: api-framework-qa
  namespace: loft-p-api-framework
spec:
  owner:
    user: admin
  templateRef:
    name: vcluster-pro-template
    version: 1.0.x
  clusterRef:
    cluster: loft-cluster
  parameters: |
    k8sVersion: v1.27.9
    env: 'qa'