apiVersion: management.loft.sh/v1
kind: App
metadata:
  name: argocd
spec:
  displayName: ArgoCD
  description: Argo CD is a declarative, GitOps continuous delivery tool for Kubernetes
  recommendedApp:
    - virtualcluster
  defaultNamespace: argocd
  icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
  config:
    chart:
      name: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
    values: '{{ .Values.appValues }}'
  versions:
    - version: 3.1.1
      defaultNamespace: argocd
      icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
      config:
        chart:
          name: argo-cd
          version: 8.3.3
          repoURL: https://argoproj.github.io/argo-helm
        values: '{{ .Values.appValues }}'
      parameters:
        - variable: appValues
          label: Helm Values
          description: The helm values to use to deploy this chart.
          type: multiline
          defaultValue: |-
            server:
              ingress:
                enabled: true
                hosts:
                - my-domain.com
    - version: 3.1.9
      defaultNamespace: argocd
      icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
      config:
        chart:
          name: argo-cd
          version: 9.0.5
          repoURL: https://argoproj.github.io/argo-helm
        values: '{{ .Values.appValues }}'
      parameters:
        - variable: appValues
          label: Helm Values
          description: The helm values to use to deploy this chart.
          type: multiline
          defaultValue: |-
            server:
              ingress:
                enabled: true
                hosts:
                - my-domain.com
    - version: 2.14.2
      defaultNamespace: argocd
      icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
      config:
        chart:
          name: argo-cd
          version: 7.8.2
          repoURL: https://argoproj.github.io/argo-helm
        values: '{{ .Values.appValues }}'
      parameters:
        - variable: appValues
          label: Helm Values
          description: The helm values to use to deploy this chart.
          type: multiline
          defaultValue: |-
            server:
              ingress:
                enabled: true
                hosts:
                - my-domain.com
  access:
    - verbs:
        - get
      users:
        - '*'
