apiVersion: management.loft.sh/v1
kind: App
metadata:
  name: github-repo-argo-cd-webhooks
spec:
  displayName: GitHub Repo with Argo CD Webhooks
  owner:
    team: loft-admins
  config:
    chart: {}
    bash:
      script: >

        while ! kubectl get crd applicationsets.argoproj.io; do
          echo "Waiting for argo cd applicationset crd...";
          sleep 1; 
        done

        while ! kubectl get secret ghcr-login-secret -n vcluster-platform; do
        
          echo "Waiting for ghcr-login-secret...";
          
          sleep 1; 
          
        done

        kubectl rollout status deployment/argocd-repo-server -n argocd --timeout=180s
        kubectl rollout status statefulset/argocd-application-controller -n argocd --timeout=180s

        # optional but nice: verify service endpoints actually exist
        while [ -z "$(kubectl get endpoints argocd-repo-server -n argocd -o jsonpath='{.subsets[*].addresses[*].ip}')" ]; do
          echo "Waiting for argocd-repo-server endpoints..."
          sleep 2
        done

        PULL_SECRET=$(kubectl get secret ghcr-login-secret -n vcluster-platform -o
        jsonpath="{.data['\.dockerconfigjson']}")

        cat <<EOF | kubectl apply -f -

        apiVersion: argoproj.io/v1alpha1

        kind: Application

        metadata:
          name: vcluster-gitops
          namespace: argocd
        spec:
          destination:
            server: https://kubernetes.default.svc
          project: default
          source:
            path: vcluster-gitops
            repoURL: https://github.com/loft-demos/{{ .Values.loft.virtualClusterName }}-app.git
            targetRevision: HEAD
            kustomize:
              patches:
                - target:
                    kind: SharedSecret
                    name: ghcr-login-secret
                  patch: |-
                    - op: replace
                      path: /spec/data/.dockerconfigjson
                      value: $PULL_SECRET
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
            - CreateNamespace=true
            retry:
              limit: 14
              backoff:
                duration: 2s 
                factor: 2 
                maxDuration: 2m
        EOF
