apiVersion: management.loft.sh/v1
kind: App
metadata:
  name: vcluster-platform-demo
spec:
  displayName: vCluster Platform Demo
  description: >-
    vCluster Platform Hierarchical Demo Environment.
  owner:
    team: loft-admins
  recommendedApp:
    - virtualcluster
  defaultNamespace: vcluster-platform
  icon: https://www.vcluster.com/pro/docs/media/vclusterpro_orange.svg
  config:
    chart:
      name: vcluster-platform
      repoURL: https://charts.loft.sh/
  versions:
    - version: 4.5.2
      icon: https://raw.githubusercontent.com/loft-demos/loft-demo-base/refs/heads/main/logos/vCluster_Horizontal_2colors_reversed-2.svg
      defaultNamespace: vcluster-platform
      config:
        chart:
          name: vcluster-platform
          version: 4.5.2
          repoURL: https://charts.loft.sh/
        values: |-
          admin:
            create: true

          isolation:
            enabled: true
            networkPolicy:
              enabled: false
              
          resources:
            requests:
              memory: 2Gi
              cpu: 500m
            limits:
              memory: 6Gi
              cpu: "2"

          ingress:
            enabled: true
            ingressClass: nginx
            host: "{{ .Values.domain }}"
            tls:
              enabled: true
              secret: ""
              
          insecureSkipVerify: true

          env:
            SLEEP_MODE_LAST_ACTIVITY_UPDATE_INTERVAL: "1m"

          envValueFrom:
            CLIENT_SECRET:
              secretKeyRef:
                name: oidc-secret
                key: clientSecret

          config:
            loftHost: "{{ .Values.domain }}"
            costControl:
              enabled: true
            imageBuilder:
              enabled: false
            uiSettings:
              navBarButtons:
              - link: https://www.vcluster.com/docs/platform/
                position: TopEnd
                text: vCluster Docs
              - link: https://github.com/loft-demos/{{ .Values.loft.virtualClusterName }}-app/tree/main/vcluster-gitops
                position: TopEnd
                text: GitHub Repo
              - link: https://headlamp-{{ .Values.domain }}
                position: TopEnd
                text: Headlamp
              - link: https://komoplane-{{ .Values.domain }}
                position: TopEnd
                text: Komoplane
              logoURL: "{{ .Values.uiLogoURL }}"
              logoBackgroundColor: "{{ .Values.logoBackgroundColor }}"
            auth:
              oidc:
                issuerUrl: https://loft.rocks/oidc
                clientId: loft
                clientSecret: $CLIENT_SECRET
                redirectURI: https://{{ .Values.domain }}/auth/oidc/callback
                groupsClaim: groups
      parameters:
        - variable: domain
          label: Loft Domain
          description: >-
            The domain to run this Loft instance on, e.g.
            some-customer.loft.host
          required: true
          placeholder: some-customer.loft.host
        - variable: uiLogoURL
          label: Logo logoURL
          description: Will update the vCluster Platform config ui settings logoURL
          defaultValue: https://raw.githubusercontent.com/loft-demos/loft-demo-base/refs/heads/main/logos/vCluster_Horizontal_2colors_reversed-2.svg
        - variable: logoBackgroundColor
          label: Logo Background Color
          description: LogoBackgroundColor is the color value to use as the background color for the logo
          defaultValue: '#001529'
    - version: 4.4.0
      icon: https://raw.githubusercontent.com/loft-demos/loft-demo-base/refs/heads/main/logos/vCluster_Horizontal_2colors_reversed-2.svg
      defaultNamespace: vcluster-platform
      config:
        chart:
          name: vcluster-platform
          version: 4.4.0
          repoURL: https://charts.loft.sh/
        values: |-
          admin:
            create: true

          isolation:
            enabled: true
            networkPolicy:
              enabled: false
              
          resources:
            requests:
              memory: 2Gi
              cpu: 500m
            limits:
              memory: 6Gi
              cpu: "2"

          ingress:
            enabled: true
            ingressClass: nginx
            host: "{{ .Values.domain }}"
            tls:
              enabled: true
              secret: ""
              
          insecureSkipVerify: true

          envValueFrom:
            CLIENT_SECRET:
              secretKeyRef:
                name: oidc-secret
                key: clientSecret

          config:
            loftHost: "{{ .Values.domain }}"
            costControl:
              enabled: true
            imageBuilder:
              enabled: false
            uiSettings:
              navBarButtons:
              - link: https://www.vcluster.com/docs/platform/
                position: TopEnd
                text: vCluster Docs
              - link: https://github.com/loft-demos/{{ .Values.loft.virtualClusterName }}-app/tree/main/vcluster-gitops
                position: TopEnd
                text: GitHub Repo
              - link: https://headlamp-{{ .Values.domain }}
                position: TopEnd
                text: Headlamp
              - link: https://komoplane-{{ .Values.domain }}
                position: TopEnd
                text: Komoplane
              logoURL: "{{ .Values.uiLogoURL }}"
              logoBackgroundColor: "{{ .Values.logoBackgroundColor }}"
            auth:
              oidc:
                issuerUrl: https://loft.rocks/oidc
                clientId: loft
                clientSecret: $CLIENT_SECRET
                redirectURI: https://{{ .Values.domain }}/auth/oidc/callback
                groupsClaim: groups
      parameters:
        - variable: domain
          label: Loft Domain
          description: >-
            The domain to run this Loft instance on, e.g.
            some-customer.loft.host
          required: true
          placeholder: some-customer.loft.host
        - variable: uiLogoURL
          label: Logo logoURL
          description: Will update the vCluster Platform config ui settings logoURL
          defaultValue: https://raw.githubusercontent.com/loft-demos/loft-demo-base/refs/heads/main/logos/vCluster_Horizontal_2colors_reversed-2.svg
        - variable: logoBackgroundColor
          label: Logo Background Color
          description: LogoBackgroundColor is the color value to use as the background color for the logo
          defaultValue: '#001529'
    - version: 4.5.1
      icon: https://raw.githubusercontent.com/loft-demos/loft-demo-base/refs/heads/main/logos/vCluster_Horizontal_2colors_reversed-2.svg
      defaultNamespace: vcluster-platform
      config:
        chart:
          name: vcluster-platform
          version: 4.5.1
          repoURL: https://charts.loft.sh/
        values: |-
          admin:
            create: true

          isolation:
            enabled: true
            networkPolicy:
              enabled: false
              
          resources:
            requests:
              memory: 2Gi
              cpu: 500m
            limits:
              memory: 6Gi
              cpu: "2"

          ingress:
            enabled: true
            ingressClass: nginx
            host: "{{ .Values.domain }}"
            tls:
              enabled: true
              secret: ""
              
          insecureSkipVerify: true

          env:
            SLEEP_MODE_LAST_ACTIVITY_UPDATE_INTERVAL: "1m"

          envValueFrom:
            CLIENT_SECRET:
              secretKeyRef:
                name: oidc-secret
                key: clientSecret

          config:
            loftHost: "{{ .Values.domain }}"
            costControl:
              enabled: true
            imageBuilder:
              enabled: false
            uiSettings:
              navBarButtons:
              - link: https://www.vcluster.com/docs/platform/
                position: TopEnd
                text: vCluster Docs
              - link: https://github.com/loft-demos/{{ .Values.loft.virtualClusterName }}-app/tree/main/vcluster-gitops
                position: TopEnd
                text: GitHub Repo
              - link: https://headlamp-{{ .Values.domain }}
                position: TopEnd
                text: Headlamp
              - link: https://komoplane-{{ .Values.domain }}
                position: TopEnd
                text: Komoplane
              logoURL: "{{ .Values.uiLogoURL }}"
              logoBackgroundColor: "{{ .Values.logoBackgroundColor }}"
            auth:
              oidc:
                issuerUrl: https://loft.rocks/oidc
                clientId: loft
                clientSecret: $CLIENT_SECRET
                redirectURI: https://{{ .Values.domain }}/auth/oidc/callback
                groupsClaim: groups
      parameters:
        - variable: domain
          label: Loft Domain
          description: >-
            The domain to run this Loft instance on, e.g.
            some-customer.loft.host
          required: true
          placeholder: some-customer.loft.host
        - variable: uiLogoURL
          label: Logo logoURL
          description: Will update the vCluster Platform config ui settings logoURL
          defaultValue: https://raw.githubusercontent.com/loft-demos/loft-demo-base/refs/heads/main/logos/vCluster_Horizontal_2colors_reversed-2.svg
        - variable: logoBackgroundColor
          label: Logo Background Color
          description: LogoBackgroundColor is the color value to use as the background color for the logo
          defaultValue: '#001529'
    - version: 0.460.5
      icon: https://raw.githubusercontent.com/loft-demos/loft-demo-base/refs/heads/main/logos/vCluster_Horizontal_2colors_reversed-2.svg
      defaultNamespace: vcluster-platform
      config:
        chart:
          name: vcluster-platform
          version: 4.6.0-alpha.5
          repoURL: https://charts.loft.sh/
        values: |-
          admin:
            create: true

          isolation:
            enabled: true
            networkPolicy:
              enabled: false
              
          resources:
            requests:
              memory: 2Gi
              cpu: 500m
            limits:
              memory: 6Gi
              cpu: "2"

          ingress:
            enabled: true
            ingressClass: nginx
            host: "{{ .Values.domain }}"
            tls:
              enabled: true
              secret: ""
              
          insecureSkipVerify: true

          envValueFrom:
            CLIENT_SECRET:
              secretKeyRef:
                name: oidc-secret
                key: clientSecret

          config:
            loftHost: "{{ .Values.domain }}"
            costControl:
              enabled: true
            imageBuilder:
              enabled: false
            uiSettings:
              navBarButtons:
              - link: https://www.vcluster.com/docs/platform/
                position: TopEnd
                text: vCluster Docs
              - link: https://github.com/loft-demos/{{ .Values.loft.virtualClusterName }}-app/tree/main/vcluster-gitops
                position: TopEnd
                text: GitHub Repo
              - link: https://headlamp-{{ .Values.domain }}
                position: TopEnd
                text: Headlamp
              - link: https://komoplane-{{ .Values.domain }}
                position: TopEnd
                text: Komoplane
              logoURL: "{{ .Values.uiLogoURL }}"
              logoBackgroundColor: "{{ .Values.logoBackgroundColor }}"
            auth:
              oidc:
                issuerUrl: https://loft.rocks/oidc
                clientId: loft
                clientSecret: $CLIENT_SECRET
                redirectURI: https://{{ .Values.domain }}/auth/oidc/callback
                groupsClaim: groups
      parameters:
        - variable: domain
          label: Loft Domain
          description: >-
            The domain to run this Loft instance on, e.g.
            some-customer.loft.host
          required: true
          placeholder: some-customer.loft.host
        - variable: uiLogoURL
          label: Logo logoURL
          description: Will update the vCluster Platform config ui settings logoURL
          defaultValue: https://raw.githubusercontent.com/loft-demos/loft-demo-base/refs/heads/main/logos/vCluster_Horizontal_2colors_reversed-2.svg
        - variable: logoBackgroundColor
          label: Logo Background Color
          description: LogoBackgroundColor is the color value to use as the background color for the logo
          defaultValue: '#001529'
    - version: 0.460.7
      icon: https://raw.githubusercontent.com/loft-demos/loft-demo-base/refs/heads/main/logos/vCluster_Horizontal_2colors_reversed-2.svg
      defaultNamespace: vcluster-platform
      config:
        chart:
          name: vcluster-platform
          version: 4.6.0-alpha.7
          repoURL: https://charts.loft.sh/
        values: |-
          admin:
            create: true

          isolation:
            enabled: true
            networkPolicy:
              enabled: false
              
          resources:
            requests:
              memory: 2Gi
              cpu: 500m
            limits:
              memory: 6Gi
              cpu: "2"

          ingress:
            enabled: true
            ingressClass: nginx
            host: "{{ .Values.domain }}"
            tls:
              enabled: true
              secret: ""
              
          insecureSkipVerify: true

          envValueFrom:
            CLIENT_SECRET:
              secretKeyRef:
                name: oidc-secret
                key: clientSecret

          config:
            loftHost: "{{ .Values.domain }}"
            costControl:
              enabled: true
            imageBuilder:
              enabled: false
            uiSettings:
              navBarButtons:
              - link: https://www.vcluster.com/docs/platform/
                position: TopEnd
                text: vCluster Docs
              - link: https://github.com/loft-demos/{{ .Values.loft.virtualClusterName }}-app/tree/main/vcluster-gitops
                position: TopEnd
                text: GitHub Repo
              - link: https://headlamp-{{ .Values.domain }}
                position: TopEnd
                text: Headlamp
              - link: https://komoplane-{{ .Values.domain }}
                position: TopEnd
                text: Komoplane
              logoURL: "{{ .Values.uiLogoURL }}"
              logoBackgroundColor: "{{ .Values.logoBackgroundColor }}"
            auth:
              oidc:
                issuerUrl: https://loft.rocks/oidc
                clientId: loft
                clientSecret: $CLIENT_SECRET
                redirectURI: https://{{ .Values.domain }}/auth/oidc/callback
                groupsClaim: groups
      parameters:
        - variable: domain
          label: Loft Domain
          description: >-
            The domain to run this Loft instance on, e.g.
            some-customer.loft.host
          required: true
          placeholder: some-customer.loft.host
        - variable: uiLogoURL
          label: Logo logoURL
          description: Will update the vCluster Platform config ui settings logoURL
          defaultValue: https://raw.githubusercontent.com/loft-demos/loft-demo-base/refs/heads/main/logos/vCluster_Horizontal_2colors_reversed-2.svg
        - variable: logoBackgroundColor
          label: Logo Background Color
          description: LogoBackgroundColor is the color value to use as the background color for the logo
          defaultValue: '#001529'
    - version: 1.460.3
      icon: https://raw.githubusercontent.com/loft-demos/loft-demo-base/refs/heads/main/logos/vCluster_Horizontal_2colors_reversed-2.svg
      defaultNamespace: vcluster-platform
      config:
        chart:
          name: vcluster-platform
          version: 4.6.0-next.3
          repoURL: https://charts.loft.sh/
        values: |-
          admin:
            create: true

          isolation:
            enabled: true
            networkPolicy:
              enabled: false
              
          resources:
            requests:
              memory: 2Gi
              cpu: 500m
            limits:
              memory: 6Gi
              cpu: "2"

          ingress:
            enabled: true
            ingressClass: nginx
            host: "{{ .Values.domain }}"
            tls:
              enabled: true
              secret: ""
              
          insecureSkipVerify: true

          envValueFrom:
            CLIENT_SECRET:
              secretKeyRef:
                name: oidc-secret
                key: clientSecret

          config:
            loftHost: "{{ .Values.domain }}"
            costControl:
              enabled: true
            imageBuilder:
              enabled: false
            uiSettings:
              navBarButtons:
              - link: https://www.vcluster.com/docs/platform/
                position: TopEnd
                text: vCluster Docs
              - link: https://github.com/loft-demos/{{ .Values.loft.virtualClusterName }}-app/tree/main/vcluster-gitops
                position: TopEnd
                text: GitHub Repo
              - link: https://headlamp-{{ .Values.domain }}
                position: TopEnd
                text: Headlamp
              - link: https://komoplane-{{ .Values.domain }}
                position: TopEnd
                text: Komoplane
              logoURL: "{{ .Values.uiLogoURL }}"
              logoBackgroundColor: "{{ .Values.logoBackgroundColor }}"
            auth:
              oidc:
                issuerUrl: https://loft.rocks/oidc
                clientId: loft
                clientSecret: $CLIENT_SECRET
                redirectURI: https://{{ .Values.domain }}/auth/oidc/callback
                groupsClaim: groups
      parameters:
        - variable: domain
          label: Loft Domain
          description: >-
            The domain to run this Loft instance on, e.g.
            some-customer.loft.host
          required: true
          placeholder: some-customer.loft.host
        - variable: uiLogoURL
          label: Logo logoURL
          description: Will update the vCluster Platform config ui settings logoURL
          defaultValue: https://raw.githubusercontent.com/loft-demos/loft-demo-base/refs/heads/main/logos/vCluster_Horizontal_2colors_reversed-2.svg
        - variable: logoBackgroundColor
          label: Logo Background Color
          description: LogoBackgroundColor is the color value to use as the background color for the logo
          defaultValue: '#001529'
