apiVersion: management.loft.sh/v1
kind: App
metadata:
  name: vcluster-platform-demo-configure-admins
spec:
  displayName: vCluster Platform Demo Configure Admins
  description: Configures SSO Groups that should get admin privileges
  owner:
    team: loft-admins
  config:
    chart: {}
    bash:
      script: >|
        kubectl wait --for condition=established --timeout=60s
        crd/teams.storage.loft.sh


        while ! kubectl get teams.storage.loft.sh loft-admins; do
          echo "Waiting for team...";
          sleep 1; 
        done


        cat <<EOF | kubectl apply -f -

        kind: Team

        apiVersion: storage.loft.sh/v1

        metadata:
          name: loft-admins
        spec:
          displayName: Global Admins
          description: All users in this team have full admin access to all clusters
          username: loftadmins
          groups:
            - loft:admins
            - Administration
            - Design
            - DevRel
            - Engineering
            - Marketing
            - Product
            - Sales
          clusterRoles:
            - name: loft-management-admin
          access:
            - name: loft-access
              verbs:
                - get
                - bind
              subresources:
                - clusters
              teams:
                - loft-admins
        EOF

        while ! kubectl get secret demo-admin-access-key -n vcluster-platform; do
        
          echo "Waiting for demo-admin-access-key...";
          
          sleep 1; 
          
        done

        ACCESS_KEY=$(kubectl get secret demo-admin-access-key -n vcluster-platform -o
        jsonpath="{.data['accessKey']}")

        echo "acess key before patch: $ACCESS_KEY"

        TIMEOUT=60
        SLEEP=2
        
        end=$((SECONDS+TIMEOUT))
        
        echo "[INFO] Waiting until OwnedAccessKey can be created..."
        
        while (( SECONDS < end )); do
        
          if kubectl api-resources --api-group=management.loft.sh \
            | grep -q '^ownedaccesskeys'; then
            
            if kubectl auth can-i --quiet create ownedaccesskeys.management.loft.sh; then
            
              echo "[INFO] OwnedAccessKey is creatable."
              
              break
              
            fi
            
          fi
          
          sleep "$SLEEP"
          
        done


        OUTPUT=$(cat <<EOF | kubectl apply -f -

        apiVersion: management.loft.sh/v1
        
        kind: OwnedAccessKey
        
        metadata:
          creationTimestamp: null
          name: "demo-env-admin-access-key"
        spec:
          displayName: "demo-env-admin-access-key"
          type: User
          team: loft-admins
          key: $ACCESS_KEY
        status: {}
        
        EOF
        
        )

        RESOURCE_NAME=$(echo "$OUTPUT" | awk '{print $1}' | cut -d'/' -f2)


        kubectl patch accesskey.storage.loft.sh $RESOURCE_NAME \
          --type='merge' \
          -p='{"spec":{"key":"'"$ACCESS_KEY"'"}}'

        ACCESS_KEY=$(kubectl get accesskey $RESOURCE_NAME  -o jsonpath="{.spec.key}")

        echo "acess key after patch: $ACCESS_KEY"

        kubectl annotate clusters loft-cluster domainPrefix={{
        .Values.loft.virtualClusterName }}

        kubectl annotate clusters loft-cluster domain={{
        .Values.loft.clusterAnnotations.domain }}
