apiVersion: management.loft.sh/v1
kind: App
metadata:
  name: vcluster-platform-partner
spec:
  displayName: vCluster Platform Partner Demo
  description: >-
    vCluster Platform Partner Demo Environment.
  owner:
    team: loft-admins
  recommendedApp:
    - virtualcluster
  defaultNamespace: vcluster-platform
  icon: https://www.vcluster.com/pro/docs/media/vclusterpro_orange.svg
  config:
    chart:
      name: vcluster-platform
      repoURL: https://charts.loft.sh/
  versions:
    - version: 4.7.0
      icon: https://raw.githubusercontent.com/loft-demos/loft-demo-base/refs/heads/main/logos/vCluster_Horizontal_2colors_reversed-2.svg
      defaultNamespace: vcluster-platform
      config:
        chart:
          name: vcluster-platform
          version: 4.7.0
          repoURL: https://charts.loft.sh/
        values: |-
          admin:
            create: true
            username: admin

          isolation:
            enabled: true
            networkPolicy:
              enabled: false
              
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 2Gi
              cpu: "2"

          ingress:
            enabled: true
            ingressClass: nginx
            host: '{{ .Values.domain }}'
            tls:
              enabled: true
              secret: ""
              
          insecureSkipVerify: true

          config:
            loftHost: '{{ .Values.domain }}'
            costControl:
              enabled: false
            imageBuilder:
              enabled: false
            uiSettings:
              navBarButtons:
              - link: https://www.vcluster.com/docs/platform/
                position: TopEnd
                text: vCluster Docs
              - link: 'https://github.com/loft-demos/{{ .Values.loft.virtualClusterName }}-app/tree/main/vcluster-gitops'
                position: TopEnd
                text: GitHub Repo
              logoURL: '{{ .Values.uiLogoURL }}'
              logoBackgroundColor: '{{ .Values.logoBackgroundColor }}'
      parameters:
        - variable: domain
          label: vCluster Platform Domain
          description: >-
            The domain to run this Loft instance on, e.g.
            some-customer.loft.host
          required: true
          placeholder: some-customer.loft.host
        - variable: uiLogoURL
          label: Logo logoURL
          description: Will update the vCluster Platform config ui settings logoURL
        - variable: logoBackgroundColor
          label: Logo Background Color
          description: LogoBackgroundColor is the color value to use as the background color for the logo
          defaultValue: '#001529'
