apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: APPLICATION_NAME
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 
    targetRevision: main
    path: helm-chart
  destination: 
    name: loft-api-framework-vcluster-api-framework-qa
    namespace: PREVIEW_NAMESPACE

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: false
      prune: false